//! # Data Models
//!
//! This module defines the core types that flow through the system:
//! job posts from crawlers, the user's resume, match results, scan history,
//! user preferences, CLI commands, and the company database.
//!
//! All types implement [`Serialize`] and [`Deserialize`] so they can be
//! persisted to `~/.jobsense-parker/` as JSON between sessions.
//!
//! # Type Relationships
//!
//! ```text
//!  ┌────────────┐     ┌──────────────┐     ┌─────────────┐
//!  │ SearchConfig│────▶│  SourceCrawler │────▶│  JobPost[]   │
//!  └────────────┘     └──────────────┘     └──────┬──────┘
//!                                                  │
//!  ┌──────────┐                                   │
//!  │  Resume  │────▶ Matcher.score_all() ─────────┤
//!  └──────────┘                                   │
//!                                                  ▼
    //!                                          ┌─────────────┐
//!                                          │ MatchResult[] │──▶ displayed
//!                                          └─────────────┘    in vim viewer
//! ```

use chrono::{DateTime, Utc};
use regex::Regex;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ─── Job Source ────────────────────────────────────────────────────────────

/// Identifies **where** a job posting was discovered.
///
/// Each crawler sets this field on every [`JobPost`] it produces so the UI
/// can show the source badge (e.g. `[Remote OK]`, `[Reddit]`, `[Hacker News]`).
///
/// # Display format
///
/// Used in the results viewer to tag each result:
///
/// ```text
///  1. Senior Rust Engineer 78% [Remote OK] @ Stripe
///                               ^^^^^^^^^^^
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum JobSource {
    /// Jobs from [Remote OK](https://remoteok.com) — tagged JSON API.
    RemoteOk,
    /// Jobs from Reddit hiring subreddits (`r/forhire`, `r/jobbit`, etc.).
    Reddit,
    /// Jobs from Hacker News monthly "Who is Hiring?" threads.
    HackerNews,
    /// Jobs from a user-defined or dynamic source (e.g. a company career site).
    Custom(String),
}

impl std::fmt::Display for JobSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::RemoteOk => write!(f, "Remote OK"),
            Self::Reddit => write!(f, "Reddit"),
            Self::HackerNews => write!(f, "Hacker News"),
            Self::Custom(s) => write!(f, "{s}"),
        }
    }
}

// ─── Job Post ──────────────────────────────────────────────────────────────

/// A single job posting collected by a source crawler.
///
/// This is the primary data unit that flows from crawlers → matcher → viewer.
///
/// # Fields
///
/// | Field | Source | Example |
/// |-------|--------|---------|
/// | `title` | Always set | `"Senior Rust Engineer"` |
/// | `company` | Remote OK ✓, HN ✓, Reddit ✗ | `"Stripe"` |
/// | `location` | Remote OK ✓, others rarely | `"San Francisco, CA"` |
/// | `description` | HN ✓ (comment text), Remote OK ✓ (HTML stripped), Reddit ✓ (selftext) | Full job description |
/// | `salary` | Remote OK ✓ (from JSON) | `"$150k - $200k"` |
/// | `url` | Always set | Clickable link to original posting |
/// | `source` | Always set | `JobSource::RemoteOk` |
/// | `tags` | Source-specific | `["hacker-news", "who-is-hiring"]` |
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobPost {
    /// Unique identifier (UUID v4). Auto-generated by the crawler.
    pub id: String,
    /// Job title (e.g. `"Senior Rust Engineer"`, `"Software Developer"`).
    pub title: String,
    /// Company name, if the source provides it.
    ///
    /// Used for company auto-discovery: when this is `Some`, the CLI
    /// will attempt to add the company to the local database.
    pub company: Option<String>,
    /// Geographic location, if available (e.g. `"San Francisco, CA"`, `"Remote"`).
    pub location: Option<String>,
    /// Full description text (plain-text, HTML stripped).
    ///
    /// This is what the matcher scans for skill/keyword matches.
    pub description: String,
    /// Link to the original posting. Rendered as an OSC 8 clickable hyperlink.
    pub url: String,
    /// Which source this was collected from (used for UI tagging).
    pub source: JobSource,
    /// When the posting was published (if the source provides a timestamp).
    pub posted_at: Option<DateTime<Utc>>,
    /// When our crawler fetched it.
    pub crawled_at: DateTime<Utc>,
    /// Salary range as a display string (e.g. `"$80k - $120k"`, `"Up to $200k"`).
    pub salary: Option<String>,
    /// Employment type (e.g. `"full-time"`, `"contract"`) if known.
    pub job_type: Option<String>,
    /// Source-specific tags (e.g. subreddit name, tech tags from Remote OK).
    pub tags: Vec<String>,
}

// ─── Resume ────────────────────────────────────────────────────────────────

/// The user's parsed resume — skills, roles, keywords, and preferences.
///
/// Can be constructed from a plain-text string via [`Resume::from_text`],
/// from a JSON file, or from a YAML file. The parser uses regex patterns
/// to extract structured fields without any hard-coded skill list.
///
/// # Example (JSON format)
///
/// ```json
/// {
///   "skills": ["rust", "python", "docker", "kubernetes"],
///   "role_titles": ["software engineer", "senior engineer"],
///   "experience_years": 5.0,
///   "preferred_location": "San Francisco",
///   "preferred_job_type": "remote",
///   "keywords": ["rust", "python", "backend", "distributed", "systems"]
/// }
/// ```
///
/// # Example (plain text — auto-extracted)
///
/// ```text
/// I am a Senior Software Engineer with 5 years of experience in Rust and
/// Python. Proficient in Docker and Kubernetes. Based in San Francisco.
/// Looking for remote opportunities.
/// ```
///
/// Parsing this text produces a `Resume` with:
/// - skills: `["rust", "python", "docker", "kubernetes"]`
/// - role_titles: `["senior software engineer"]`
/// - experience_years: `Some(5.0)`
/// - preferred_location: `Some("san francisco")`
/// - preferred_job_type: `Some("remote")`
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Resume {
    /// Recognised technical skills (e.g. `"rust"`, `"docker"`, `"aws"`).
    ///
    /// Extracted from context patterns like:
    /// - `"experience with Rust"`
    /// - `"proficient in Python"`
    /// - `"Technologies: Rust, Python, Docker"`
    pub skills: Vec<String>,
    /// Years of professional experience extracted from text.
    ///
    /// Matches patterns like `"5 years"`, `"10+ years"`, `"3 yrs of experience"`.
    pub experience_years: Option<f32>,
    /// Role/career level indicators (e.g. `"engineer"`, `"senior"`, `"lead"`).
    ///
    /// Extracted from patterns like `"Senior Software Engineer"` in title
    /// lines or `"Role: Lead Developer"` headers.
    pub role_titles: Vec<String>,
    /// All significant keywords extracted from the resume text.
    ///
    /// These are all alphanumeric tokens (3+ chars) with common stop words
    /// filtered out. Used for broad matching against job descriptions.
    pub keywords: Vec<String>,
    /// Preferred work location, if mentioned in the resume.
    ///
    /// Matches patterns like `"based in NYC"`, `"located in San Francisco"`.
    pub preferred_location: Option<String>,
    /// Preferred employment type, if mentioned (e.g. `"remote"`, `"full-time"`).
    pub preferred_job_type: Option<String>,
    /// Minimum acceptable salary, if known. Currently unused in scoring.
    pub min_salary: Option<u64>,
}

impl Resume {
    /// Parse a plain-text resume and extract structured fields.
    ///
    /// Uses regex patterns to infer skills, roles, experience years, location,
    /// job type, and keywords. No hard-coded skill list — everything is
    /// context-derived.
    ///
    /// # Extraction Rules
    ///
    /// | Field | Pattern | Example Input → Output |
    /// |-------|---------|----------------------|
    /// | Skills | `"experience with X"`, `"proficient in X"` | `"experience with Rust"` → `"rust"` |
    /// | Skills | `"Technologies: X, Y, Z"` | `"Technologies: Rust, Python"` → `["rust", "python"]` |
    /// | Roles | `"Senior X Engineer"` in context | `"Senior Software Engineer"` → `"senior software engineer"` |
    /// | Exp | `"N years of experience"` | `"5 years of experience"` → `Some(5.0)` |
    /// | Location | `"based in X"`, `"located in X"` | `"based in NYC"` → `Some("nyc")` |
    /// | Job type | `"looking for remote"` | `"looking for remote"` → `Some("remote")` |
    ///
    /// # Example
    ///
    /// ```
    /// use jobsense_parker::models::Resume;
    ///
    /// let text = "Senior Software Engineer with 5 years of experience. \
    ///             Proficient in Rust, Python, and Docker. Based in NYC.";
    /// let resume = Resume::from_text(text);
    ///
    /// assert!(resume.skills.contains(&"rust".to_string()));
    /// assert!(resume.role_titles.contains(&"senior software engineer".to_string()));
    /// assert_eq!(resume.experience_years, Some(5.0));
    /// ```
    pub fn from_text(text: &str) -> Self {
        let lower = text.to_lowercase();
        Self {
            skills: Self::extract_skills(&lower),
            role_titles: Self::extract_roles(&lower),
            experience_years: Self::extract_experience_years(&lower),
            preferred_location: Self::extract_location(&lower),
            preferred_job_type: Self::extract_job_type(&lower),
            keywords: Self::extract_keywords(text),
            min_salary: None,
        }
    }

    /// Extract skills from context cues like `"experience with Rust"` or
    /// `"Technologies: Rust, Python, Docker"`.
    fn extract_skills(text: &str) -> Vec<String> {
        let mut skills: Vec<String> = Vec::new();

        // Pattern: "experience with X", "proficient in X", "knowledge of X", etc.
        let ctx_re = Regex::new(
            r"(?i)(?:experience|proficient|skills?|knowledge|worked|familiar|expertise|strong|fluent|background|expert|using|including)\s*(?:with|in|at|using|of|on|including)\s+([a-z][a-z+#.]+(?:\s+[a-z][a-z+#.]+)?)"
        ).unwrap();
        for cap in ctx_re.captures_iter(text) {
            let s = cap.get(1).unwrap().as_str().trim().to_string();
            if s.len() >= 2 {
                skills.push(s);
            }
        }

        // Pattern: "Technologies: Rust, Python", "Languages: Go, TypeScript"
        let list_re = Regex::new(
            r"(?i)(?:technolog(y|ies)|tools?|tech\s*stack|languages?|frameworks?|platforms?)[:\s]+(.+)"
        ).unwrap();
        if let Some(caps) = list_re.captures(text) {
            let list_part = caps.get(2).unwrap().as_str();
            for item in list_part.split([',', ';', '|', '\n']).filter_map(|s| {
                let t = s.trim().trim_matches(|c: char| c == '.' || c == ' ').to_string();
                (t.len() >= 2 && !t.contains(char::is_whitespace)).then_some(t)
            }) {
                skills.push(item);
            }
        }

        skills.sort_unstable();
        skills.dedup();
        skills
    }

    /// Extract role titles from patterns like `"Senior Software Engineer"`,
    /// `"Role: Lead Developer"`, or `"Data Scientist"`.
    fn extract_roles(text: &str) -> Vec<String> {
        let mut roles: Vec<String> = Vec::new();

        // "Role: Senior Engineer", "Position: Lead Developer"
        let ctx_re = Regex::new(
            r"(?i)(?:role|position|title)[:\s]+([a-z]+\s+(?:engineer|developer|architect|manager|lead|intern|analyst|consultant|scientist|designer|director|head))"
        ).unwrap();
        for cap in ctx_re.captures_iter(text) {
            roles.push(cap.get(1).unwrap().as_str().trim().to_string());
        }

        // "Senior Software Engineer", "Frontend Developer", "Data Scientist"
        let title_re = Regex::new(
            r"(?i)(?:(?:senior|staff|principal|lead|junior|intern|head)\s+)?(?:software|data|full.?stack|frontend|backend|devops|platform|security|systems|network|site\s*reliability|machine\s*learning|ai|ml)\s+(?:engineer|developer|architect|manager|scientist|analyst)"
        ).unwrap();
        for cap in title_re.captures_iter(text) {
            let role = cap.get(0).unwrap().as_str().trim().to_string();
            if !roles.contains(&role) {
                roles.push(role);
            }
        }

        roles.sort_unstable();
        roles.dedup();
        roles
    }

    /// Extract years of experience from patterns like `"5 years"`, `"10+ yrs"`.
    fn extract_experience_years(text: &str) -> Option<f32> {
        let re = Regex::new(r"(?i)(\d+)\+?\s*(?:years?|yrs?)\s*(?:of\s+)?(?:experience|exp)").unwrap();
        re.captures(text)
            .and_then(|c| c.get(1)?.as_str().parse::<f32>().ok())
    }

    /// Extract preferred location from patterns like `"based in NYC"`, `"located in SF"`.
    fn extract_location(text: &str) -> Option<String> {
        let re = Regex::new(
            r"(?i)(?:based|located|living|situated)\s+(?:in|at|near)\s+([a-z][a-z\s.-]+?)(?:[,.!]|$)"
        ).unwrap();
        re.captures(text).and_then(|c| {
            let loc = c.get(1)?.as_str().trim().to_string();
            (loc.len() <= 50).then_some(loc)
        })
    }

    /// Extract preferred job type from patterns like `"looking for remote"` or
    /// fall back to scanning for keywords like "full-time", "contract".
    fn extract_job_type(text: &str) -> Option<String> {
        let re = Regex::new(
            r"(?i)(?:looking|seeking|want|prefer|open|available)\s+(?:for|a|an)?\s*(full[- ]time|part[- ]time|contract|remote|hybrid|onsite)"
        ).unwrap();
        if let Some(cap) = re.captures(text) {
            return cap.get(1).map(|m| m.as_str().to_string());
        }
        // Fallback: scan for keywords directly
        for t in &["full-time", "full time", "part-time", "part time", "contract", "remote", "hybrid", "onsite"] {
            if text.contains(t) {
                return Some(t.to_string());
            }
        }
        None
    }

    /// Extract significant keywords (3+ chars, no stop words).
    fn extract_keywords(text: &str) -> Vec<String> {
        let stop_words = [
            "the", "and", "for", "are", "but", "not", "you", "all", "can", "had", "her",
            "was", "one", "our", "out", "has", "have", "been", "some", "same", "also",
            "its", "than", "them", "into", "two", "more", "these", "like", "over",
            "such", "that", "this", "with", "from", "your", "which", "each", "will",
            "about", "between", "under", "very", "just", "their", "would", "after",
            "could", "should", "other", "than", "then", "there", "where", "while",
            "because", "before", "does", "doing", "done", "much", "many", "most",
            "must", "need", "take", "make", "made", "well", "work", "year", "years",
        ];
        let mut keywords: Vec<String> = text
            .split(|c: char| !c.is_alphanumeric() && c != '+' && c != '#')
            .filter(|w| w.len() >= 3)
            .map(|w| w.to_lowercase())
            .filter(|w| !stop_words.contains(&w.as_str()))
            .collect();
        keywords.sort_unstable();
        keywords.dedup();
        keywords
    }
}

// ─── Search Config ─────────────────────────────────────────────────────────

/// Configuration for a single crawl/search operation.
///
/// Passed to every [`SourceCrawler::crawl`] so each crawler knows what the
/// user is looking for. Also used for post-filtering in [`CrawlerCoordinator`].
///
/// # Default
///
/// ```ignore
/// SearchConfig {
///     keywords:     vec![],                              // user must provide
///     sources:      [RemoteOk, Reddit, HackerNews],     // all three boards
///     max_results:  50,                                  // per source
///     max_days_old: Some(7),                             // last week
///     location:     None,
///     remote_only:  false,
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchConfig {
    /// Keywords to search for across sources. Space-separated in CLI queries.
    ///
    /// Used for:
    /// - Remote OK: fetches tag-based pages (`/remote-{keyword}-jobs.json`)
    /// - Reddit: URL query parameter on `/search.json`
    /// - HN: Algolia query parameter appended to "Who is Hiring" search
    /// - Company crawler: post-filtering on extracted job titles
    /// - All sources: post-filtering in [`CrawlerCoordinator::crawl_all`]
    pub keywords: Vec<String>,
    /// Which sources to include in the search. Defaults to all three boards.
    pub sources: Vec<JobSource>,
    /// Maximum number of job posts to collect **per source**.
    pub max_results: usize,
    /// Maximum age of job posts in days (`None` = no limit).
    pub max_days_old: Option<i64>,
    /// Geographic preference to narrow results (currently advisory).
    pub location: Option<String>,
    /// Whether to filter for remote-only positions (currently advisory).
    pub remote_only: bool,
}

impl Default for SearchConfig {
    fn default() -> Self {
        Self {
            keywords: vec![],
            sources: vec![
                JobSource::RemoteOk,
                JobSource::Reddit,
                JobSource::HackerNews,
            ],
            max_results: 50,
            max_days_old: Some(7),
            location: None,
            remote_only: false,
        }
    }
}

// ─── Match Result ─────────────────────────────────────────────────────────

/// The output of matching a [`JobPost`] against a [`Resume`].
///
/// Produced by [`Matcher::score_all`]. Each result has a compatibility score
/// between 0.0 (no match) and 1.0 (perfect match), plus details on which
/// skills matched and which are missing.
///
/// # Score Interpretation
///
/// | Range | Meaning | Colour in UI |
/// |-------|---------|-------------|
/// | 0.70 – 1.00 | Strong match | Green |
/// | 0.40 – 0.69 | Moderate match | Yellow |
/// | 0.00 – 0.39 | Weak match | Dimmed |
/// | < 0.15 | Filtered out (below threshold) | — |
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MatchResult {
    /// The job post that was matched.
    pub job: JobPost,
    /// Overall compatibility score (0.0 – 1.0).
    ///
    /// Computed as a weighted sum:
    /// - Skill ratio: 50%
    /// - Keyword ratio: 25%
    /// - Role-title match: 10%
    /// - Location match: 10%
    /// - Job-type match: 5%
    pub score: f64,
    /// Skills from the resume that were found in the job description.
    pub matched_skills: Vec<String>,
    /// Keywords from the resume that were found in the job description.
    pub matched_keywords: Vec<String>,
    /// Skills from the resume that were NOT found in the job description.
    pub missing_skills: Vec<String>,
}

// ─── Scan Record ───────────────────────────────────────────────────────────

/// A single scan session — what was searched, when, and the outcome.
///
/// Persisted in `~/.jobsense-parker/scan_history.json` and displayed via
/// `--history` or the interactive menu. Capped at 100 records.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanRecord {
    /// Unique scan identifier (UUID v4).
    pub id: String,
    /// When the scan was performed.
    pub timestamp: DateTime<Utc>,
    /// The query string used during the scan.
    pub query: String,
    /// Number of sources crawled.
    pub source_count: usize,
    /// Total raw jobs found before matching.
    pub total_jobs_found: usize,
    /// The highest match score across all results.
    pub top_score: f64,
    /// Number of results that passed the threshold.
    pub result_count: usize,
}

// ─── CLI Command ───────────────────────────────────────────────────────────

/// A command issued by the user via the interactive menu or CLI arguments.
///
/// The [`App`](crate::cli::App) main loop converts user input into these
/// commands and dispatches them to the corresponding handler methods.
#[derive(Debug, Clone, PartialEq)]
pub enum Command {
    /// Run a scan against all configured sources + company career sites.
    Scan,
    /// Search with a custom query string (space-separated keywords).
    Search(String),
    /// Display the last scan results in the vim-style paginated viewer.
    ViewResults,
    /// Load a resume from a file path or raw text.
    LoadResume(String),
    /// Show the currently loaded resume (skills, roles, preferences).
    ShowResume,
    /// Filter/sort the current results by score range.
    FilterResults,
    /// List all cached companies with their careers-page URLs and crawl status.
    ListCompanies,
    /// Add a company to the cache manually (name + careers URL).
    AddCompany(String, String),
    /// Remove a company from the cache by name.
    RemoveCompany(String),
    /// Exit the application.
    Quit,
}

// ─── User Preferences ──────────────────────────────────────────────────────

/// Persisted user preferences that survive between sessions.
///
/// Stored in `~/.jobsense-parker/preferences.json`. Currently loaded at
/// startup but not yet exposed through the interactive menu for editing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserPreferences {
    /// Preferred work location (e.g. `"San Francisco"`, `"Remote"`).
    pub preferred_location: Option<String>,
    /// Preferred employment type (e.g. `"remote"`, `"full-time"`).
    pub preferred_job_type: Option<String>,
    /// Minimum acceptable salary.
    pub min_salary: Option<u64>,
    /// Which sources to search by default (used to initialise [`SearchConfig`]).
    pub active_sources: Vec<JobSource>,
    /// Maximum results per scan.
    pub max_results: usize,
}

impl Default for UserPreferences {
    fn default() -> Self {
        Self {
            preferred_location: None,
            preferred_job_type: None,
            min_salary: None,
            active_sources: vec![
                JobSource::RemoteOk,
                JobSource::Reddit,
                JobSource::HackerNews,
            ],
            max_results: 50,
        }
    }
}

// ─── Company / Career-Site Crawling ────────────────────────────────────────

/// A company whose career site we track and crawl for job listings.
///
/// Companies are either:
/// - **Pre-seeded** (80+ major tech companies on first run)
/// - **Auto-discovered** from job posts found during scans
/// - **Manually added** via `--add-company` or the interactive menu
///
/// Each company has a careers-page URL that the [`CompanyCrawler`](crate::crawler::company::CompanyCrawler)
/// fetches and parses using heuristics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Company {
    /// Display name (e.g. `"Google"`, `"Stripe"`, `"Jane Street"`).
    pub name: String,
    /// URL to the careers/jobs page (e.g. `"https://careers.google.com/jobs"`).
    pub careers_url: String,
    /// When this company was first discovered or added.
    pub added_at: DateTime<Utc>,
    /// Last time we successfully crawled their career page.
    ///
    /// `None` means the company was never crawled yet.
    /// Companies are re-crawled at most once per hour.
    pub last_crawled: Option<DateTime<Utc>>,
}

/// The persisted cache of known companies with their career-site URLs.
///
/// Stored in `~/.jobsense-parker/companies.json`. Auto-seeded with 80+ major
/// tech companies on first run. Grows as new companies are discovered.
///
/// # Capacity
///
/// Auto-discovery stops at 100 companies to prevent bloat. Manual addition
/// has no limit.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CompanyDatabase {
    /// The list of tracked companies.
    pub companies: Vec<Company>,
    /// Companies whose last crawl attempt failed (name → error message).
    ///
    /// Displayed in the company list with a ⚠ warning icon.
    pub failed: HashMap<String, String>,
}

impl CompanyDatabase {
    /// Create an empty database.
    pub fn new() -> Self {
        Self {
            companies: Vec::new(),
            failed: HashMap::new(),
        }
    }

    /// Add a company to the database.
    ///
    /// Returns `false` if the company is already present (case-insensitive).
    /// Clears any previous failure record for this company.
    ///
    /// # Example
    ///
    /// ```ignore
    /// db.add("Tesla", "https://www.tesla.com/careers");
    /// assert!(!db.add("tesla", "https://www.tesla.com/careers")); // duplicate
    /// ```
    pub fn add(&mut self, name: &str, careers_url: &str) -> bool {
        if self.companies.iter().any(|c| c.name.eq_ignore_ascii_case(name)) {
            return false;
        }
        self.companies.push(Company {
            name: name.to_string(),
            careers_url: careers_url.to_string(),
            added_at: Utc::now(),
            last_crawled: None,
        });
        self.failed.remove(name);
        true
    }

    /// Remove a company by name (case-insensitive).
    ///
    /// Returns `true` if the company was removed, `false` if not found.
    pub fn remove(&mut self, name: &str) -> bool {
        let before = self.companies.len();
        self.companies.retain(|c| !c.name.eq_ignore_ascii_case(name));
        self.failed.remove(name);
        before != self.companies.len()
    }

    /// Mark a company crawl as successful (updates `last_crawled`).
    pub fn mark_crawled(&mut self, name: &str) {
        self.failed.remove(name);
        if let Some(c) = self.companies.iter_mut().find(|c| c.name.eq_ignore_ascii_case(name)) {
            c.last_crawled = Some(Utc::now());
        }
    }

    /// Mark a company crawl as failed (stores error for display).
    pub fn mark_failed(&mut self, name: &str, error: &str) {
        self.failed.insert(name.to_string(), error.to_string());
    }
}
